OHDSI/ArachneUI

src/modules/AnalysisExecution/components/ViewEditAnalysis/ListCode/selectors.js
src/modules/StudyManager/components/ViewEdit/ModalAddDataSource/VirtualSource/selectors.js

ARACHNE-1309

---

src/modules/StudyManager/components/ViewEdit/ListAnalyses/presenter.jsx
src/modules/StudyManager/components/ViewEdit/ListAnalyses/selectors.js
src/modules/StudyManager/components/ViewEdit/ListAnalyses/style.scss

add created date time and author to analyses list item

ARACHNE-1339

---

src/components/FileInfo/converter.js
src/modules/AnalysisExecution/components/ViewEditAnalysis/ListSubmissions/presenter.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/ListSubmissions/selectors.js
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalFiles/container.js

(cherry picked from commit 1dd621d)

Fixed submission result deleting for manually added files

---

test/java/com/odysseusinc/arachne/portal/front/BaseDataSourceTest.java
test/java/com/odysseusinc/arachne/portal/front/BaseStudyNotebookTest.java
test/java/com/odysseusinc/arachne/portal/front/BaseStudyTest.java
test/java/com/odysseusinc/arachne/portal/front/BaseTest.java
test/java/com/odysseusinc/arachne/portal/front/BaseUserTest.java
test/java/com/odysseusinc/arachne/portal/front/ProfileManagerTest.java
test/java/com/odysseusinc/arachne/portal/front/StudyManagerTest.java
test/java/com/odysseusinc/arachne/portal/front/utils/ByBuilder.java

Arachne 1293 selenium for study edit

---

src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalFiles/container.js
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalFiles/presenter.jsx

Fixed non obvious labels in analysis code files modal

Fixed caching of query in analysis code files modal

---

src/bootstrap.jsx

fix logoutBug of expired token

ARACHNE-1430

---

src/modules/InsightsLibrary/components/ViewEdit/ModalSettings/container.js
src/modules/InsightsLibrary/components/ViewEdit/ModalSettings/presenter.jsx
src/modules/InsightsLibrary/components/ViewEdit/ModalSettings/style.scss
src/modules/StudyManager/components/ViewEdit/Actions/container.js

allow to add draft insights to active study

ARACHNE-1404

---

package.json
src/modules/AnalysisExecution/components/ViewEditInsight/ListCode/presenter.jsx

fix files presenter in insights

ARACHNE-1469

---

package.json
src/modules/ExpertFinder/components/ProfileView/Skills/container.js

upd skills list after add/remove

Arachne 1475

---

package.json
src/modules/ExpertFinder/components/MenuDropdown/container.js
src/modules/ExpertFinder/components/MenuDropdown/presenter.jsx
src/modules/ExpertFinder/components/ProfileView/UserPicModal/container.js

ARACHNE-1599

---

package.json
src/components/FiltersList/presenter.jsx

ARACHNE-1581

---

package.json
src/components/FiltersList/presenter.jsx

fix filters page refreshing
for debugging it in test env

Arachne 1581 to dev

---

src/modules/AnalysisExecution/const.js

ARACHNE-1603 - Cohort Characterization import

---

src/modules/CdmSourceList/components/List/ModalCreateEdit/container.js
src/modules/CdmSourceList/components/ViewEdit/Characterization/container.js

ARACHNE-1608

---

package.json
src/modules/Auth/ducks/token.js

Arachne 1537

---

package.json
src/modules/CdmSourceList/components/ViewEdit/container.js
src/modules/CdmSourceList/components/ViewEdit/presenter.jsx

show achilles only on registered DS

ARACHNE-1663

---

src/bootstrap.jsx
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Incidence/presenter.jsx
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Incidence/style.scss
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/presenter.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/ListSubmissions/Results/presenter.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/ListSubmissions/Results/style.scss

Changed the view of the IR summary

Fixed pluralization of the 'Person'

---

src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Incidence/style.scss
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/PopulationLevel/style.scss
src/modules/AnalysisExecution/ducks/submissionFileDuckBuilder.js
src/styles/vars-and-mixins.scss

added border to table in summary

fixed error in ducks

---

src/components/Reports/Observations/ObservationsDetails/presenter.jsx
src/components/Reports/converters/dataToMonthLineChartData.js

ARACHNE-1814 Achilles reports not render data

ARACHNE-1813 Achilles reports display exception

---

src/modules/AnalysisExecution/const.js
src/modules/Portal/index.jsx

removed unused code from Node side

Added analysis name for CUSTOM

---

src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Cohort/presenter.jsx
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Incidence/presenter.jsx
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/container.js
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/presenter.jsx
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/selectors.js
src/modules/AnalysisExecution/const.js
src/modules/AnalysisExecution/ducks/index.js
src/modules/AnalysisExecution/ducks/submissionSummary.js
src/modules/AnalysisExecution/ducks/summary.js
webpack/app.config.js

moved vendor chunking to production build

use separate endpoints for submission info & short analysis info

---

package.json
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalSubmitCode/container.js

added upating of the submissions list after submitting new submission

---

package.json
src/components/PasswordField/style.scss
src/modules/Auth/const.js
src/modules/Portal/components/Settings/FormPassword/presenter.jsx

removed unnesessary password hints

fixed icon

---

src/components/FiltersList/filter-form.js
src/modules/DataCatalog/components/ViewEdit/View/Report/presenter.jsx

ARACHNE-2152 Show full-text search filter in badged iconhe result list
ARACHNE-2167 Filtering by DS Execution Policy doesn't work
ARACHNE-2172 Achilles reports dropdown can be unselected (should not be so)

ARACHNE-2150 Study filtering by public/private does not affect

---

package.json
src/modules/DataCatalog/components/ViewEdit/View/ModalInviteToStudy/presenter.jsx
src/modules/DataCatalog/components/ViewEdit/View/ModalInviteToStudy/style.scss

ARACHNE-2173 Cannot switch between Achilles
needs to be replaced by npm package (^1.2.0)

temp fix for

---

src/components/Reports/converters/dataToBoxplotData.js
src/components/VirtualScroller/components/Table/style.scss
src/modules/CdmSourceList/components/List/ModalCreateEdit/style.scss
src/modules/DataCatalog/components/ViewEdit/View/Report/container.js
src/modules/Portal/components/Search/NavbarInput/container.js
src/modules/Portal/components/Search/Results/List/selectors.js

ARACHNE-2184 Global search icon doesn't open input
ARACHNE-2185 Markup issue in Import popup
ARACHNE-2149 Achilles reports - Drug eras error

ARACHNE-2168 [CENTRAL] default ds achilles report

---

src/modules/DataCatalog/components/MyDatasources/selectors.js

ARACHNE-2199 [front] [central] pagination of my ds

fixed pagination of the my datasources list

---

package.json
src/components/FileInfo/presenter.jsx
src/components/VirtualScroller/components/Table/stateful.js
src/components/VirtualScroller/components/Table/style.scss
src/modules/DataCatalog/components/List/presenter.jsx
src/modules/DataCatalog/components/List/style.scss
src/modules/StudyManager/components/ViewEdit/ModalAddDataSource/DataCatalogSource/container.js

ARACHNE-2220 Data catalog columns width issue

ARACHNE-2219 Tooltip for file name

---

package.json
src/modules/Admin/index.js
src/modules/Admin/routesCentral.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/ListSubmissions/components/SubmissionsTableFilter/container.js
src/modules/CdmSourceList/components/List/Table/presenter.jsx
src/modules/DataCatalog/components/MyDatasources/presenter.jsx
src/modules/DataCatalog/components/ViewEdit/View/Report/container.js
src/modules/DataCatalog/components/ViewEdit/View/container.js
src/modules/ExpertFinder/components/ProfileView/ContactInfo/Edit/container.js
src/modules/ExpertFinder/components/ProfileView/ContactInfo/Edit/presenter.jsx
src/modules/ExpertFinder/components/ProfileView/ContactInfo/View/container.js
src/modules/ExpertFinder/components/ProfileView/presenter.jsx

ARACHNE-2257 Direct navigation to DS reports page doesn't load any report
ARACHNE-2263 State is not shown in users profile
ARACHNE-2264 Submissions filter: clicking Any should automatically select all, and it should be selected by default
ARACHNE-2262 Disable States field and show appropriate tooltip while Country is not specified in Users profile
ARACHNE-2246 Clicking on admin setting twice gives a blank screen
ARACHNE-2255 Loader is not displayed for loading of characterization data at a DS page
ARACHNE-2251 Fix width of DS name column
ARACHNE-2250 Rename "Reports" button to "Achilles" at DN side

ARACHNE-2265 QA: I can delete data source without any confirmation!

---

package.json
src/modules/Admin/components/PortalUserList/ModalAddUser/container.js
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalSubmitCode/container.js
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalSubmitCode/presenter.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalSubmitCode/style.scss
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalUploadResult/container.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/Settings/presenter.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/container.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/presenter.jsx
src/modules/DataCatalog/components/MyDatasources/components/ModalCreateDataSource/container.js
src/modules/StudyManager/components/ViewEdit/ModalAddDataSource/DataCatalogSource/container.js
src/modules/StudyManager/components/ViewEdit/ModalAddDataSource/VirtualSource/container.js
src/modules/StudyManager/components/ViewEdit/ModalAddDataSource/presenter.jsx

ARACHNE-2094 Allow user to request DS access from submission panel
ARACHNE-2274 No validation of the equality of the entered passwords
ARACHNE-2278 Redirect to new DS edit (publish) page after manual DS was created
ARACHNE-2279 Submissions data is not refreshed after Data Owner attaches a file to submission to Manual DS

ARACHNE-2271 Code lock markup issue

---

package.json
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalSubmitCode/presenter.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalSubmitCode/style.scss
src/modules/DataCatalog/components/MyDatasources/components/ModalCreateDataSource/container.js
src/modules/DataCatalog/components/MyDatasources/style.scss
src/modules/DataCatalog/components/ViewEdit/View/Report/container.js

fixed Achilles stats loading
finxed pagination position in my ds list

fixed Invite DS button position

---

package.json
src/components/Grid/presenter.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/ListSubmissions/components/SubmissionsTableFilter/container.js

fixed submission table filters

ARACHNE-2300 QA: Fix bug with pager counter

---

src/modules/Admin/components/SystemSettings/presenter.jsx

Arachne 2354 reindex button in admin panel

---

src/modules/ExpertFinder/components/ProfileView/Skills/container.js
src/modules/ExpertFinder/components/ProfileView/Skills/presenter.jsx

disabled 'Add' button if no skill is chosen
added hint text after creation new skill

ARACHNE-2484. Fixed 'add skill' behaviour

---

src/modules/Admin/components/PortalUserList/ModalAddUserBatch/presenter.jsx
src/modules/DataCatalog/components/DataNode/ViewEdit/components/EditDataNodeTitle/container.js
src/modules/DataCatalog/components/DataNode/ViewEdit/container.js

ARACHNE-2482. Added asterisk for mandatory fields in batch user uploading dialog

---

package.json

changed components version to 1.13.37

changed version to 1.13.81

---

src/modules/AnalysisExecution/components/ViewEditAnalysis/ListCode/style.scss

Fixed height of code files list

---

src/modules/CdmSourceList/components/List/ModalCreateEdit/container.js

Fixed prefilling of data in edit DS form

---

src/modules/Admin/components/PortalUserList/ModalAddUser/style.scss
src/modules/StudyManager/components/List/CreateModal/style.scss
src/modules/StudyManager/components/ViewEdit/ModalAddParticipant/style.scss
src/modules/StudyManager/components/ViewEdit/ModalCreateAnalysis/style.scss
src/styles/vars-and-mixins.scss

Fixed markup issue with modal dropdowns

---

src/modules/AnalysisExecution/components/ViewEditAnalysis/ListCode/presenter.jsx

Fixed loader when reimporting analysis

---

src/components/CodeEditor/style.scss
src/components/MediaViewer/style.scss
src/const/antivirus.js
src/styles/vars-and-mixins.scss

Fixed tooltip for Download button

---

src/components/MediaViewer/style.scss

Fixed user menu rendering

---

src/components/VirtualScroller/components/Table/presenter.jsx
src/components/VirtualScroller/components/Table/stateful.js

Fixed horizontal scrollbar on reload

---

src/components/VirtualScroller/components/Table/presenter.jsx
src/components/VirtualScroller/components/Table/stateful.js
src/components/VirtualScroller/components/Table/style.scss
src/styles/vars-and-mixins.scss

Fixed styling for csv table

---

src/components/MediaViewer/CsvViewer/presenter.jsx
src/components/VirtualScroller/components/Table/stateful.js

fixes https://github.com/OHDSI/ArachneUI/issues/650

Fixed Import list in Analysis

---

src/components/VirtualScroller/components/Table/stateful.js

Fixed Import list in Analysis (container height recursion)

---

src/AppContainer.jsx
src/components/FileBrowser/style.scss
src/components/MediaViewer/CsvViewer/presenter.jsx
src/components/MediaViewer/presenter.jsx
src/components/VirtualScroller/components/Table/presenter.jsx
src/components/VirtualScroller/components/Table/stateful.js
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/style.scss

fixes https://github.com/OHDSI/ArachneUI/issues/654
tests:

Fixes layout of Analysis Summary when CSV viewer is used

---

src/modules/StudyManager/components/ViewEdit/ModalAddDataSource/DataCatalogSource/style.scss

Fixed bottom padding in 'Add data source' modal

---

src/modules/DataCatalog/components/DataSource/MyDatasources/components/ModalCreateDataSource/style.scss

Fixed 'Add manual datasource' modal

---

package.json

bump npm package version for publishing to npmjs.org

bump npm package version for publishing

---

README.md

Update readme documentation for the Community Edition
closes #547

Update readme documentation for the Community Edition

---

package.json
src/modules/Auth/ducks/token.js

Implements synchronous token refresh to prevent expired token usage attempts
related to OHDSI/ArachneNodeAPI#328

Authenticator utilization, sync token refresh

---

package.json
src/components/FileTree/presenter.jsx
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/selectors.js
src/modules/AnalysisExecution/components/ViewEditAnalysis/ListSubmissions/Results/presenter.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalUploadResult/const.js
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalUploadResult/container.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalUploadResult/presenter.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalUploadResult/style.scss

Also https://github.com/OHDSI/ArachneUIComponents/pull/137
Fixes https://github.com/OHDSI/ArachneCentralAPI/issues/615

Added ability to upload zip with result files

---

src/modules/Submissions/components/List/ModalСreateSubmission/container.js
src/modules/Submissions/components/List/ModalСreateSubmission/presenter.jsx
src/modules/Submissions/components/List/ModalСreateSubmission/style.scss
src/modules/Submissions/const.js
src/modules/Submissions/ducks/index.js
src/modules/Submissions/ducks/tabs.js
src/services/Utils.js

Fixes https://github.com/OHDSI/ArachneNodeAPI/issues/332

Added ability to submit unarchived files for execution

---

package-lock.json
package.json
src/AppContainer.jsx
src/modules/Admin/components/AdminList/ModalAddUser/container.js
src/modules/Admin/components/AdminList/ModalAddUser/selectors.js
src/modules/Admin/components/AdminList/Table/container.js
src/modules/Admin/components/AdminList/Table/presenter.jsx
src/modules/Admin/components/AdminList/container.jsx
src/modules/Auth/components/Login/FormLogin/container.js
src/modules/Auth/components/Login/FormLogin/presenter.jsx
src/modules/Auth/components/Login/container.js
src/modules/Auth/const.js
src/modules/Auth/ducks/index.js
src/modules/Auth/ducks/nodeMode.js
src/modules/CdmSourceList/components/List/Table/container.js
src/modules/CdmSourceList/components/List/Table/presenter.jsx
src/modules/CdmSourceList/components/List/Table/style.scss
src/modules/CdmSourceList/components/ViewEdit/Characterization/container.js
src/modules/CdmSourceList/components/ViewEdit/Characterization/presenter.jsx
src/services/Api.js

Related to OHDSI/ArachneNodeAPI#328

adds support for Node standalone mode

---

src/modules/CdmSourceList/components/ViewEdit/container.js

Fixes Data source details are not cleaned up from DS creation popup

---

src/const/dataSource.js
src/modules/CdmSourceList/components/List/ModalCreateEdit/container.js
src/modules/CdmSourceList/components/List/ModalCreateEdit/presenter.jsx

Fixes OHDSI/ArachneNodeAPI#333

Fixes Failure when DataSource updating in Network mode

---

src/components/Reports/Measurement/container.js

Datasource measurement treemap drilldown function is broken due to the wrong path

fix drilldown details retrieval for measurements

---

package.json

update npm package version to 1.15.16

update npm packages version to 1.15.16

---

package.json
src/const/dataSource.js

expose version 5.3.1 in UI -DS grid and search facet

support CDM 531 in UI

---

src/modules/Admin/components/AdminList/ModalAddUser/style.scss
src/modules/AnalysisExecution/components/ViewEditAnalysis/ListCode/style.scss

Added scroll to code files list

---

package-lock.json
package.json
pom.xml
src/AppContainer.jsx
src/bootstrap.jsx
src/modules/Auth/components/Logout/container.jsx
src/modules/Auth/components/Logout/presenter.jsx
src/modules/Auth/components/Logout/style.scss
src/modules/Auth/const.js
src/modules/Auth/ducks/authMode.js
src/modules/Auth/ducks/index.js

- Arachne 2729 iap auth support

Arachne 2729 iap auth support

---

src/modules/StudyManager/components/ViewEdit/ListParticipants/presenter.jsx
src/modules/StudyManager/components/ViewEdit/ListParticipants/style.scss

redesign participant list
group participant and his roles with extended comments

redesign participant list 

---

package.json
src/bootstrap.jsx

- fix for handel user not authorized exception

ARACHNE-2729 Add IAP auth support into Standalone Node

---

package.json
src/modules/Portal/components/Settings/FormPassword/container.js

Show a standard Arachne notification for the successful password update

Password update notification

---

package.json
src/modules/Portal/components/Settings/FormPassword/container.js

add notification for password update

add notification for password update

---

package.json
src/modules/StudyManager/components/ViewEdit/Actions/container.js

fix delete study by id action call

fix delete study by id action

---

package.json
src/modules/StudyManager/components/ViewEdit/ListParticipants/presenter.jsx
src/modules/StudyManager/components/ViewEdit/ListParticipants/style.scss

redesign participants tab version with faces

redesign participants tab version with faces

---

package.json
src/modules/StudyManager/components/ViewEdit/ListParticipants/style.scss

redesign participants style tweaks

redesign participants style tweaks

---

package.json
src/modules/StudyManager/components/ViewEdit/ListParticipants/presenter.jsx
src/modules/StudyManager/components/ViewEdit/ListParticipants/style.scss

redesign participants view changes

redesign participants view changes

---

package.json
src/modules/StudyManager/components/ViewEdit/ListParticipants/presenter.jsx
src/modules/StudyManager/components/ViewEdit/ListParticipants/style.scss

Redesign participants views changes

Redesign participants views changes

---

package.json
src/modules/StudyManager/components/ViewEdit/ListParticipants/presenter.jsx
src/modules/StudyManager/components/ViewEdit/ListParticipants/style.scss

Redesign participant views changes

Redesign partisipant views changes

---

src/modules/Portal/components/Settings/FormPassword/presenter.jsx
src/services/Utils.js

show password confirmation validation error only for password confirmation field

show password confirmation validation error only once

---

src/modules/Admin/components/PortalUserList/Table/ActionsToolbar/presenter.jsx
src/modules/Admin/components/PortalUserList/Table/ActionsToolbar/style.scss

support soft-delete mode for the users which have FK references and cannot be removed completely

support users soft-delete

---

package.json
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalCreateCode/Import/ImportLoading/container.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalCreateCode/Import/ImportLoading/presenter.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalCreateCode/Import/ImportLoading/style.scss
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalCreateCode/Import/container.js
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalCreateCode/Import/presenter.jsx

analyses import error closes #660

analyses import error

---

package.json

update version to deploy recent changes

Update package.json  version

---

package.json
src/modules/Admin/components/PortalUserList/Filters/fields.js
src/modules/Admin/components/PortalUserList/Table/ActionsToolbar/presenter.jsx
src/modules/Admin/components/PortalUserList/Table/ActionsToolbar/style.scss

Users administration filtering improvements

Users administration filtering improvements

---

package.json
src/components/VirtualScroller/components/List/style.scss
src/modules/AnalysisExecution/components/ViewEditAnalysis/ModalCreateCode/Import/ImportList/style.scss
src/styles/appContainer.scss

Accept after https://github.com/OHDSI/ArachneUI/pull/726

Fixed multiple scrollbars when modal is opened

---

package.json
src/modules/AnalysisExecution/components/ViewEditAnalysis/ListSubmissions/Results/presenter.jsx

Also https://github.com/OHDSI/ArachneUIComponents/pull/152

Fixed number formatting

---

src/modules/AnalysisExecution/const.js

fix typo in the status label

---

package-lock.json
src/bootstrap.jsx
src/modules/Auth/components/Logout/container.jsx
src/modules/Auth/components/Logout/presenter.jsx
src/modules/Auth/components/Logout/style.scss

QA 1.16.0 fix merge

---

package-lock.json
package.json
src/modules/ExternalResourceManager/components/AtlasList/ModalCreateEdit/container.jsx
src/modules/ExternalResourceManager/components/AtlasList/ModalCreateEdit/presenter.jsx
src/modules/ExternalResourceManager/const.js

Closes OHDSI/ArachneNodeAPI#400

Implements Atlas Google oauth authentication

---

package-lock.json
package.json
pom.xml
src/AppContainer.jsx
src/modules/ExternalResourceManager/components/AtlasList/ModalCreateEdit/container.jsx
src/modules/ExternalResourceManager/components/AtlasList/ModalCreateEdit/presenter.jsx
src/modules/ExternalResourceManager/const.js

update codebase version to the 1.16.1

Init 1.16.1

---

src/modules/Portal/components/Settings/container.js
src/modules/Portal/components/Settings/index.js
src/modules/Portal/components/Settings/presenter.jsx

refactor settings to class component to make it extendable

refactor settings to class component 

---

package.json
src/modules/Portal/components/Settings/presenter.jsx

refactor base settings page

---

src/modules/Admin/components/PortalUserList/ModalAddUserBatch/presenter.jsx
src/modules/Auth/const.js

Make mobile phone not mandatory

Make mobile phone not mandatory

---

src/modules/StudyManager/components/ViewEdit/container.js

fix routing logic for the transition to study/workspace

fix routing logic for the transition to study/workspace

---

src/modules/StudyManager/components/ViewEdit/ListDataSources/container.js
src/modules/StudyManager/components/ViewEdit/ModalAddDataSource/DataCatalogSource/container.js
src/modules/StudyManager/components/ViewEdit/ModalAddDataSource/VirtualSource/container.js

implement proper study/workspace reload

implement proper study/workspace reload

---

src/modules/StudyManager/components/Workspace/Toolbar/container.js

reload workspace fix

---

src/modules/StudyManager/components/ViewEdit/ModalAddParticipant/presenter.jsx

change participant role select mode

change participant role select mode

---

pom.xml

set version to 1.16.2-snapshot

set version to 1.16.2-snapshot

---

src/const/formats.js

https://odysseusdataservices.atlassian.net/browse/ARACHNE-2852

fix format for tables

---

src/modules/Submissions/components/List/Table/style.scss

Fixed analysis cell styles in submissions table

[arachne-2845] Fixed analysis name display in submissions table

---

package.json
src/AppContainer.jsx
src/components/Guarded/presenter.jsx
src/modules/CdmSourceList/components/List/Table/presenter.jsx
src/modules/DataCatalog/components/DataSource/List/Table/presenter.jsx

https://odysseusdataservices.atlassian.net/browse/ARACHNE-2856

Arachne 2856

---

src/modules/Submissions/components/List/Table/style.scss

added styles for author study and data-source cell of submission table

Arachne-2845 Fix cells of submission table

---

src/modules/ExpertFinder/components/ExpertsList/List/ExpertCard/presenter.jsx
src/modules/InsightsLibrary/components/List/container.js
src/modules/Portal/components/MenuDropdown/presenter.jsx

Fixed prop types at expert finder page

---

src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/container.js
src/modules/AnalysisExecution/const.js
src/modules/AnalysisExecution/ducks/index.js
src/modules/AnalysisExecution/ducks/linkBuilder.js
src/modules/AnalysisExecution/ducks/submissionResultZipEntry.js

Full Heracles analysis with the drilldown details in the zip parts

Heracles Drilldown reports in the zip files

---

src/components/DatePanel/presenter.jsx
src/components/InviteRestrictedArea/container.js
src/components/PasswordField/presenter.jsx
src/components/People/presenter.jsx
src/modules/Admin/components/PortalUserList/Table/ActionsToolbar/presenter.jsx
src/modules/Admin/components/PortalUserList/Table/presenter.jsx
src/modules/Admin/components/PortalUserList/presenter.jsx
src/modules/Admin/components/SystemSettings/selectors.js
src/modules/CdmSourceList/components/List/Table/presenter.jsx
src/modules/InsightsLibrary/components/List/List/components/Cards/presenter.jsx
src/modules/InsightsLibrary/components/List/List/components/Table/fields.jsx
src/modules/InsightsLibrary/components/ViewEdit/ModalSettings/presenter.jsx
src/modules/InsightsLibrary/components/ViewEdit/Toolbar/ToolbarActions/actions.jsx
src/modules/InsightsLibrary/components/ViewEdit/Toolbar/ToolbarActions/presenter.jsx
src/modules/InsightsLibrary/components/ViewEdit/participants.jsx
src/modules/StudyManager/components/List/List/components/Table/presenter.jsx
src/modules/StudyManager/components/ViewEdit/Actions/container.js
src/modules/StudyManager/components/ViewEdit/ListParticipants/presenter.jsx
src/modules/StudyManager/components/ViewEdit/ModalAddDataSource/DataCatalogSource/presenter.jsx
src/modules/StudyManager/components/ViewEdit/ModalCreateDocument/presenter.jsx
src/modules/StudyManager/components/ViewEdit/Settings/presenter.jsx
src/modules/StudyManager/components/Workspace/Toolbar/presenter.jsx
src/modules/Submissions/components/List/Table/presenter.jsx

Relates to https://github.com/OHDSI/ArachneUIComponents/pull/164

Fixed prop types

---

src/components/Reports/DrugEra/DrugEraDetails/container.js
src/components/Reports/DrugEra/DrugEraDetails/presenter.jsx
src/components/Reports/DrugEra/container.js
src/components/Reports/DrugEra/presenter.jsx
src/components/Reports/Procedures/ProceduresDetails/presenter.jsx
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/converters/DTO.js

DrugEra report fixes
misc namings

DrugEra report fixes

---

src/AppContainer.jsx
src/bootstrap.jsx
src/services/Duck.js

https://odysseusdataservices.atlassian.net/browse/ARACHNE-2898
added small check for loading user

Added conditions for checking of completed request of current user info

---

package-lock.json
package.json
pom.xml

update version to 1.17.0

---

src/AppContainer.jsx

Revert https://github.com/OHDSI/ArachneUI/pull/792

Removed conditions for checking of completed request of current user info

---

src/modules/DataCatalog/components/DataSource/ViewEdit/View/Report/Reports/DrugEra/selectors.js

unify usage of DrugEra drilldown part  for Heracles and Achilles

unify usage of DrugEra drilldown part  for Heracles and Achilles

---

src/components/FileTree/presenter.jsx
src/components/Reports/Chart/container.js
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Pathway/presenter.jsx

This reverts commit 96e6ffa5 due to the problem with tooltips in the achilles/heracles charts

Revert "Arachne 2928 (#798)"

---

src/components/Reports/converters/dataToScatterplotData.js
src/components/Reports/converters/index.js
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/components/DrugByIndex/DrugByIndexDetails/container.js
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/components/DrugByIndex/DrugByIndexDetails/presenter.jsx
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/components/DrugByIndex/container.js
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/components/DrugByIndex/presenter.jsx
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/components/ProceduresByIndex/ProceduresByIndexDetails/container.js
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/components/ProceduresByIndex/ProceduresByIndexDetails/presenter.jsx
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/components/ProceduresByIndex/container.js
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/components/ProceduresByIndex/presenter.jsx

update drug by index, proc by index reports details view

update drug by index, proc by index reports details view

---

src/components/Reports/BaseChart.js
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/components/ConditionsByIndex/ConditionsByIndexDetails/container.js
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/components/ConditionsByIndex/ConditionsByIndexDetails/presenter.jsx
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/components/ConditionsByIndex/container.js
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/components/ConditionsByIndex/presenter.jsx
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/components/ProceduresByIndex/ProceduresByIndexDetails/container.js

Change Heracles cond by index Details view

Conditions by index Details view

---

package-lock.json
package.json

webpack 4 fixes

---

src/modules/StudyManager/components/ViewEdit/ListParticipants/presenter.jsx

group similar participant's roles

---

helpers/publish.js
pom.xml

Update front build config

---

pom.xml

nexus update

---

package-lock.json
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/ReportViewer/selectors.js
src/modules/DataCatalog/components/DataSource/ViewEdit/View/Report/Reports/ConditionEra/selectors.js
src/modules/DataCatalog/components/DataSource/ViewEdit/View/Report/Reports/Conditions/selectors.js
src/modules/DataCatalog/components/DataSource/ViewEdit/View/Report/Reports/Drug/selectors.js
src/modules/DataCatalog/components/DataSource/ViewEdit/View/Report/Reports/DrugEra/selectors.js
src/modules/DataCatalog/components/DataSource/ViewEdit/View/Report/Reports/Measurement/selectors.js
src/modules/DataCatalog/components/DataSource/ViewEdit/View/Report/Reports/Observations/selectors.js
src/modules/DataCatalog/components/DataSource/ViewEdit/View/Report/Reports/Procedures/selectors.js
src/modules/DataCatalog/components/DataSource/ViewEdit/View/Report/Reports/Visits/selectors.js

Issue-822 Fixed adding formatting to columns

---

src/components/Reports/Person/presenter.jsx

Fixed year values in Person report

---

package-lock.json
src/const/dataSource.js
src/modules/DataCatalog/components/DataSource/ViewEdit/View/presenter.jsx

Fixed adding access type to Data Sources

---

package-lock.json
src/components/TitleStudy/icons/lock/index.js
src/components/TitleStudy/icons/lock/presenter.jsx
src/components/TitleStudy/presenter.jsx
src/modules/InsightsLibrary/components/List/List/components/Table/fields.jsx
src/modules/StudyManager/components/List/List/components/Cards/Card/presenter.jsx

fixes https://github.com/OHDSI/ArachneUI/issues/827

Fixed requiring of lock icon in Studies

---

src/modules/AnalysisExecution/components/ViewEditAnalysis/Settings/container.js
src/modules/AnalysisExecution/components/ViewEditAnalysis/Settings/presenter.jsx

Type selection will be disabled in case of one or more code files

---

src/modules/StudyManager/components/List/List/components/Table/presenter.jsx

Author name url link was removed

---

src/services/Utils.js

Error for empty password and login was fixed

---

src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Pathway/container.js

Removed multiple creation of sunburst chart

---

src/modules/AnalysisExecution/components/ViewEditAnalysis/ListSubmissions/presenter.jsx

Created HOC for sticky component

---

src/modules/AnalysisExecution/components/ViewEditAnalysis/ListSubmissions/Results/presenter.jsx
src/modules/AnalysisExecution/components/ViewEditAnalysis/ListSubmissions/presenter.jsx

fixes https://github.com/OHDSI/ArachneCentralAPI/issues/746

Changed "documents" to "files"

---

src/components/TitleStudy/presenter.jsx
src/components/TitleStudy/style.scss
src/modules/StudyManager/components/List/List/components/Table/presenter.jsx
src/modules/StudyManager/components/List/List/components/Table/style.scss

fixes #841
Hovers with full titles were added

Long titles for study title, lead and role are now truncated

---

src/modules/AnalysisExecution/components/SubmissionCodeViewer/container.js
src/modules/AnalysisExecution/components/SubmissionCodeViewer/presenter.jsx
src/modules/AnalysisExecution/components/SubmissionCodeViewer/selectors.js

fixes https://github.com/OHDSI/ArachneCentralAPI/issues/749

Changed visibility of submission results for user without approved invite

---

src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Incidence/container.js
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Incidence/index.js
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Incidence/presenter.jsx
src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Incidence/style.scss

Header of the IR result table now have dynamic elements that allow to increase and decrease ratio
